#ifndef CON_MSG_PS2D_KBD_H
#define CON_MSG_PS2D_KBD_H

typedef enum _ConsoleMessageIdPs2dKbd
{
    CON_MSG_PS2D_KBD_XMIT_INT,
    CON_MSG_PS2D_KBD_CLKS_MS,
    CON_MSG_PS2D_KBD_TM_DELAY,
    CON_MSG_PS2D_KBD_TM_RATE,
    CON_MSG_PS2D_KBD_CMD_RECV,
    CON_MSG_PS2D_KBD_RSP_SENT,
    CON_MSG_PS2D_KBD_TM_ACTIVE,
    CON_MSG_PS2D_KBD_TM_INACTIVE,
    CON_MSG_PS2D_KBD_KEYEVENT,
    CON_MSG_PS2D_KBD_BUFFER_COUNT, 
    CON_MSG_PS2D_KBD_POR_START,     
    CON_MSG_PS2D_KBD_POR_END, 
    CON_MSG_PS2D_KBD_BAT_START,     
    CON_MSG_PS2D_KBD_BAT_END, 

} ConsoleMessageIdPs2dKbd;

#endif /* CON_MSG_PS2D_KBD_H */
