#ifndef CON_MSG_PS2D_XCVR_H
#define CON_MSG_PS2D_XCVR_H

typedef enum _ConsoleMessageIdPs2dXcvr
{
    CON_MSG_PS2D_XCVR_RECV,
    CON_MSG_PS2D_XCVR_RECV_ERROR,
    CON_MSG_PS2D_XCVR_XMIT,
    CON_MSG_PS2D_XCVR_XMIT_BUFFER_FULL,
    CON_MSG_PS2D_XCVR_XMIT_BUSY,
    CON_MSG_PS2D_XCVR_REXMIT,
    CON_MSG_PS2D_XCVR_CLK_PERIOD,
} ConsoleMessageIdPs2dXcvr;

#endif /* CON_MSG_PS2D_XCVR_H */