/* =======================================================================
* ibm_scan_codes.h
*
* Purpose:
*  Declarations of IBM key positions use with scan code tables
*
* License:
*  Copyright (c) 2015, Engicoder
*  All rights reserved.
*  See LICENSE.txt for license details.
* ----------------------------------------------------------------------- */


#ifndef IBM_SCAN_CODES_H_
#define IBM_SCAN_CODES_H_

typedef enum
{
     /*  0*/   IBMKEY_ZERO,
     /*  1*/   IBMKEY_GRAVE,
     /*  2*/   IBMKEY_1,
     /*  3*/   IBMKEY_2,
     /*  4*/   IBMKEY_3,
     /*  5*/   IBMKEY_4,
     /*  6*/   IBMKEY_5,
     /*  7*/   IBMKEY_6,
     /*  8*/   IBMKEY_7,
     /*  9*/   IBMKEY_8,
     /* 10*/   IBMKEY_9,
     /* 11*/   IBMKEY_0,
     /* 12*/   IBMKEY_MINUS,
     /* 13*/   IBMKEY_EQUALS,
               IBMKEY_14,
     /* 15*/   IBMKEY_BACKSPACE,
     /* 16*/   IBMKEY_TAB,
     /* 17*/   IBMKEY_Q,
     /* 18*/   IBMKEY_W,
     /* 19*/   IBMKEY_E,
     /* 20*/   IBMKEY_R,
     /* 21*/   IBMKEY_T,
     /* 22*/   IBMKEY_Y,
     /* 23*/   IBMKEY_U,
     /* 24*/   IBMKEY_I,
     /* 25*/   IBMKEY_O,
     /* 26*/   IBMKEY_P,
     /* 27*/   IBMKEY_LBRACKET,
     /* 28*/   IBMKEY_RBRACKET,
     /* 29*/   IBMKEY_BSLASH_29,
     /* 30*/   IBMKEY_CAPSLOCK,
     /* 31*/   IBMKEY_A,
     /* 32*/   IBMKEY_S,
     /* 33*/   IBMKEY_D,
     /* 34*/   IBMKEY_F,
     /* 35*/   IBMKEY_G,
     /* 36*/   IBMKEY_H,
     /* 37*/   IBMKEY_J,
     /* 38*/   IBMKEY_K,
     /* 39*/   IBMKEY_L,
     /* 40*/   IBMKEY_SEMI,
     /* 41*/   IBMKEY_SINGLEQUOUTE,
     /* 42*/   IBMKEY_BSLASH_42,
     /* 43*/   IBMKEY_ENTER,
     /* 44*/   IBMKEY_LSHIFT,
               IBMKEY_45,   
     /* 46*/   IBMKEY_Z,
     /* 47*/   IBMKEY_X,
     /* 48*/   IBMKEY_C,
     /* 49*/   IBMKEY_V,
     /* 50*/   IBMKEY_B,
     /* 51*/   IBMKEY_N,
     /* 52*/   IBMKEY_M,
     /* 53*/   IBMKEY_COMMA,
     /* 54*/   IBMKEY_PERIOD,
     /* 55*/   IBMKEY_FSLASH,
     /* 57*/   IBMKEY_RSHIFT,
     /* 58*/   IBMKEY_LCTRL,
               IBMKEY_59,
     /* 60*/   IBMKEY_LALT,
     /* 61*/   IBMKEY_SPACE,
     /* 62*/   IBMKEY_RALT,
               IBMKEY_63,
     /* 64*/   IBMKEY_RCTRL,
               IBMKEY_65,
               IBMKEY_66,
               IBMKEY_67,
               IBMKEY_68,
               IBMKEY_69,
               IBMKEY_70,
               IBMKEY_71,
               IBMKEY_72,
               IBMKEY_73,
               IBMKEY_74,
     /* 75*/   IBMKEY_INSERT,
     /* 76*/   IBMKEY_DELELTE,
               IBMKEY_77,
               IBMKEY_78,
     /* 79*/   IBMKEY_LARROW,
     /* 80*/   IBMKEY_HOME,
     /* 81*/   IBMKEY_END,
               IBMKEY_82,
     /* 83*/   IBMKEY_UARROW,
     /* 84*/   IBMKEY_DARROW,
     /* 85*/   IBMKEY_PAGEUP,
     /* 86*/   IBMKEY_PAGEDN,
               IBMKEY_87,
               IBMKEY_88,
     /* 89*/   IBMKEY_RARROW,
     /* 90*/   IBMKEY_NUMLOCK,
     /* 91*/   IBMKEY_KP7,
     /* 92*/   IBMKEY_KP4,
     /* 93*/   IBMKEY_KP1,
               IBMKEY_94,
     /* 95*/   IBMKEY_KPDIV,
     /* 96*/   IBMKEY_KP8,
     /* 97*/   IBMKEY_KP5,
     /* 98*/   IBMKEY_KP2,
     /* 99*/   IBMKEY_KP0,
     /*100*/   IBMKEY_KPMULT,
     /*101*/   IBMKEY_KP9,
     /*102*/   IBMKEY_KP6,
     /*103*/   IBMKEY_KP3,
     /*104*/   IBMKEY_KPDECIMAL,
     /*105*/   IBMKEY_KPMINUS,
     /*106*/   IBMKEY_KPPLUS,
               IBMKEY_107,
     /*108*/   IBMKEY_KPENTER,
               IBMKEY_109,
     /*110*/   IBMKEY_ESC,
               IBMKEY_111,
     /*112*/   IBMKEY_F1,
     /*113*/   IBMKEY_F2,
     /*114*/   IBMKEY_F3,
     /*115*/   IBMKEY_F4,
     /*116*/   IBMKEY_F5,
     /*117*/   IBMKEY_F6,
     /*118*/   IBMKEY_F7,
     /*119*/   IBMKEY_F8,
     /*120*/   IBMKEY_F9,
     /*121*/   IBMKEY_F10,
     /*122*/   IBMKEY_F11,
     /*123*/   IBMKEY_F12,
     /*124*/   IBMKEY_PRTSCN,
     /*125*/   IBMKEY_SCROLLLOCK,
     /*126*/   IBMKEY_PAUSE,
     /*126*/   IBMKEY_BSLASH,
        
} IbmKey;


#endif /* IBM_SCAN_CODES_H_ */